CREATE TABLE USER_TB
(
    NICKNAME      VARCHAR2(50)     NOT NULL, 
    EMAIL         VARCHAR2(400)    NOT NULL, 
    ADDRESS1      VARCHAR2(400)    NOT NULL, 
    ADDRESS2      VARCHAR2(400)    NOT NULL, 
    ZIPCODE		  NUMBER		   NOT NULL,
    SNS			  VARCHAR2(400)	   NOT NULL,
    SNS_ID        VARCHAR2(400)    NOT NULL, 
    HOME_LAT      VARCHAR2(200)    NOT NULL, 
    HOME_LON      VARCHAR2(200)    NOT NULL, 
    FROMBUYER     VARCHAR2(20)     NOT NULL, 
    FROMSELLER    VARCHAR2(20)     NOT NULL, 
    BUYCNT        NUMBER           NOT NULL, 
    SELLCNT       NUMBER           NOT NULL, 
    CONSTRAINT USER_TB_PK PRIMARY KEY (NICKNAME),
    CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL)
)

CREATE SEQUENCE MESSAGE_TB_SEQ
START WITH 1
INCREMENT BY 1;



/

CREATE TABLE MESSAGE_TB
(
    MSG_SEQ             NUMBER            NOT NULL, 
    MSG_TITLE			VARCHAR2(50)      NOT NULL,
    MSG_CONTENT         VARCHAR2(2000)    NOT NULL, 
    SENDER              VARCHAR2(50)      NOT NULL, 
    RECEIVER            VARCHAR2(50)      NOT NULL, 
    RECEIVER_CHK        NUMBER            NOT NULL, 
    SENDER_DEL_CHK      NUMBER            NOT NULL, 
    RECEIVER_DEL_CHK    NUMBER            NOT NULL, 
    SEND_DATE           DATE              NOT NULL, 
    CONSTRAINT MESSAGE_TB_PK PRIMARY KEY (MSG_SEQ)
)
/

CREATE SEQUENCE MESSAGE_TB_SEQ
START WITH 1
INCREMENT BY 1;
/
/

ALTER TABLE MESSAGE_TB
    ADD CONSTRAINT FK_MESSAGE_TB_SENDER_USER_TB_U FOREIGN KEY (SENDER)
        REFERENCES USER_TB (USR_SEQ)
/

ALTER TABLE MESSAGE_TB
    ADD CONSTRAINT FK_MESSAGE_TB_RECEIVER_USER_TB FOREIGN KEY (RECEIVER)
        REFERENCES USER_TB (USR_SEQ)
/




CREATE TABLE SELL_BOARD_TB
(
    SELL_SEQ        NUMBER            NOT NULL, 
    SELLER          NUMBER            NULL, 
    TRADE_LAT       NUMBER            NULL, 
    TRADE_LON       NUMBER            NULL, 
    SELL_CONTENT    VARCHAR2(4000)    NULL, 
    STATUS          VARCHAR2(20)      NULL, 
    TITLE           VARCHAR2(200)     NULL, 
    REG_DATE        DATE              NULL, 
    CONSTRAINT SELL_BOARD_TB_PK PRIMARY KEY (SELL_SEQ)
)
/

CREATE SEQUENCE SELL_BOARD_TB_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER SELL_BOARD_TB_AI_TRG
BEFORE INSERT ON SELL_BOARD_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT SELL_BOARD_TB_SEQ.NEXTVAL
    INTO: NEW.SELL_SEQ
    FROM DUAL;
END;






CREATE TABLE SELL_BOARD_REPLY_TB
(
    SB_REPLY_SEQ    NUMBER            NOT NULL, 
    SB_GROUP_NUM     NUMBER            NOT NULL, 
    SB_GROUP_SEQ      NUMBER            NOT NULL, 
    SB_TITLE_TAB     NUMBER            NOT NULL, 
    SB_CONTENT      VARCHAR2(4000)    NOT NULL, 
    SB_WRITER       VARCHAR2(1000)    NOT NULL, 
    REG_DATE        DATE              NOT NULL, 
    SELL_NUM        NUMBER            NOT NULL, 
    CONSTRAINT SELL_BOARD_REPLY_TB_PK PRIMARY KEY (SB_REPLY_SEQ)
)
/

CREATE SEQUENCE SELL_BOARD_REPLY_TB_SEQ
START WITH 1
INCREMENT BY 1;
/



ALTER TABLE SELL_BOARD_REPLY_TB
    ADD CONSTRAINT FK_SELL_BOARD_REPLY_TB_SELL_NU FOREIGN KEY (SELL_NUM)
        REFERENCES SELL_BOARD_TB (SELL_SEQ)
/




CREATE TABLE DEAL_TB
(
    DEAL_SEQ      NUMBER    NOT NULL, 
    SELNUM        NUMBER    NOT NULL, 
    SELLER        NUMBER    NOT NULL, 
    BUYER         NUMBER    NOT NULL, 
    START_DATE    DATE      NOT NULL, 
    END_DATE      DATE      NOT NULL, 
    CONSTRAINT DEAL_TB_PK PRIMARY KEY (DEAL_SEQ)
)
/

CREATE SEQUENCE DEAL_TB_SEQ
START WITH 1
INCREMENT BY 1;
/





CREATE TABLE FREE_BOARD_TB
(
    FREE_SEQ           NUMBER            NOT NULL, 
    TITLE              VARCHAR2(400)     NOT NULL, 
    CONTENT            VARCHAR2(4000)    NOT NULL, 
    SAW                NUMBER            NOT NULL, 
    RECOMMEND          NUMBER            NOT NULL, 
    GROUP_NUM          NUMBER            NOT NULL, 
    GROUP_ORDER_NUM    NUMBER            NOT NULL, 
    TITLE_TAB          NUMBER            NOT NULL, 
    WRITER             NUMBER            NOT NULL, 
    REG_DATE           DATE              NULL, 
    CONSTRAINT FREE_BOARD_TB_PK PRIMARY KEY (FREE_SEQ)
)
/

CREATE SEQUENCE FREE_BOARD_TB_SEQ
START WITH 1
INCREMENT BY 1;
/



ALTER TABLE FREE_BOARD_TB
    ADD CONSTRAINT FK_FREE_BOARD_TB_WRITER_USER_T FOREIGN KEY (WRITER)
        REFERENCES USER_TB (USR_SEQ)
/



CREATE TABLE FREE_BOARD_REPLY_TB
(
    FB_REPLY_SEQ    NUMBER            NOT NULL, 
    FB_GROUP_NUM    NUMBER            NOT NULL, 
    FB_GROUP_SEQ    NUMBER            NOT NULL, 
    FB_TITLE_TAB    NUMBER            NOT NULL, 
    FB_CONTENT      VARCHAR2(4000)    NOT NULL, 
    FB_WRITER       VARCHAR2(1000)    NOT NULL, 
    REG_DATE        DATE              NOT NULL, 
    FREE_SEQ        NUMBER            NOT NULL, 
    CONSTRAINT FREE_BOARD_REPLY_TB_PK PRIMARY KEY (FB_REPLY_SEQ)
)
/

CREATE SEQUENCE FREE_BOARD_REPLY_TB_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER FREE_BOARD_REPLY_TB_AI_TRG
BEFORE INSERT ON FREE_BOARD_REPLY_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT FREE_BOARD_REPLY_TB_SEQ.NEXTVAL
    INTO: NEW.FB_REPLY_SEQ
    FROM DUAL;
END;
/


CREATE TABLE NOTICE_BOARD_TB
(
    NOTICE_SEQ    NUMBER            NOT NULL, 
    ADMIN_ID      VARCHAR2(200)     NULL, 
    TITLE         VARCHAR2(20)      NULL, 
    CONTENT       VARCHAR2(4000)    NULL, 
    SAW           NUMBER            NULL, 
    REG_DATE      DATE              NULL, 
    CONSTRAINT NOTICE_BOARD_TB_PK PRIMARY KEY (NOTICE_SEQ)
)
/

CREATE SEQUENCE NOTICE_BOARD_TB_SEQ
START WITH 1
INCREMENT BY 1;
/


CREATE OR REPLACE TRIGGER NOTICE_BOARD_TB_AI_TRG
BEFORE INSERT ON NOTICE_BOARD_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT NOTICE_BOARD_TB_SEQ.NEXTVAL
    INTO: NEW.NOTICE_SEQ
    FROM DUAL;
END;



CREATE TABLE ADMIN_TB
(
    ADMIN_ID      VARCHAR2(200)    NOT NULL, 
    ADMIN_PW      VARCHAR2(200)    NOT NULL, 
    CONSTRAINT ADMIN_TB_PK PRIMARY KEY (ADMIN_ID)
)
/



